---

- name: Create my instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: gwkeys
    instance_type: t2.micro
    security_group: connectmycloud
    image: ami-67589505
    region: ap-southeast-2
    name: MyEc2
    subnetid: subnet-ea500f8d
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnetid }}"
         assign_public_ip: yes
      register: ec2

    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_ip }}"
        groupname: launched
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 60
        timeout: 320
        state: started
      with_items: "{{ ec2.instances }}"

- name: Configure Instance
  hosts: launched
  remote_user: ec2-user

  tasks:
    - name: Install Firewalld
      yum:
        name: firewalld
        state: present
      become: yes
      become_user: root

    - name: Ensure firewall is enabled
      service:
          name: firewalld
          state: started
      become: yes
      become_user: root  

