---

# Installs Docker CE

- name: Configure Instance
  hosts: launched
  remote_user: ec2-user

  tasks:
    - name: Import Docker CE repository gpg key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present
      become: yes
      become_user: root

    - name: Add Docker CE repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        force: yes
        owner: root
        group: root
        mode: 0644
      become: yes
      become_user: root

    - name: install Docker Prerequisites
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - "yum-utils"
        - "device-mapper-persistent-data"
        - "lvm2"
        - "http://mirror.centos.org/centos/7/extras/x86_64/Packages/pigz-2.3.3-1.el7.centos.x86_64.rpm"
        - "http://mirror.centos.org/centos/7/extras/x86_64/Packages/container-selinux-2.42-1.gitad8f0f7.el7.noarch.rpm"
      become: yes
      become_user: root 
 
    - name: Install Docker CE
      yum:
        name: docker-ce
        state: present
        update_cache: yes
      become: yes
      become_user: root

    - name: Enable Docker CE service on startup
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
      become_user: root
    
